### ISSUE TITLE
Docker's Official Images build is broken

### ISSUE THREAD

**Issue by lag-linaro** [plone/plone.docker#109]
For more information please visit [Docker's Official Images Build Server](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/plone/).

Specifically the [Build Log](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/plone/60/consoleFull).

Failure:
```
Step 1/13 : FROM python:2.7-slim-stretch
 ---> 804b0a01ea83
Step 2/13 : ENV PIP 9.0.3 ZC_BUILDOUT 2.11.2 SETUPTOOLS 38.7.0 PLONE_MAJOR 5.1 PLONE_VERSION 5.1.2 PLONE_MD5 e34790cea362b8db6a8ffe30854c6fc3
 ---> Using cache
 ---> f55af302ec0c
Step 3/13 : LABEL plone $PLONE_VERSION os "debian" os.version "9" name "Plone 5.1" description "Plone image, based on Unified Installer" maintainer "Plone Community"
 ---> Using cache
 ---> 52fadf742001
Step 4/13 : RUN useradd --system -m -d /plone -U -u 500 plone  && mkdir -p /plone/instance/ /data/filestorage /data/blobstorage
 ---> Using cache
 ---> 0c99d5f66821
Step 5/13 : COPY buildout.cfg /plone/instance/
 ---> Using cache
 ---> c5f5d5ab1a8e
Step 6/13 : RUN buildDeps="dpkg-dev gcc libbz2-dev libc6-dev libjpeg62-turbo-dev libopenjp2-7-dev libpcre3-dev libssl-dev libtiff5-dev libxml2-dev libxslt1-dev wget zlib1g-dev"  && runDeps="gosu libjpeg62 libopenjp2-7 libtiff5 libxml2 libxslt1.1 lynx netcat poppler-utils rsync wv"  && apt-get update  && apt-get install -y --no-install-recommends $buildDeps  && wget -O Plone.tgz https://launchpad.net/plone/$PLONE_MAJOR/$PLONE_VERSION/+download/Plone-$PLONE_VERSION-UnifiedInstaller.tgz  && echo "$PLONE_MD5 Plone.tgz" | md5sum -c -  && tar -xzf Plone.tgz  && cp -rv ./Plone-$PLONE_VERSION-UnifiedInstaller/base_skeleton/* /plone/instance/  && cp -v ./Plone-$PLONE_VERSION-UnifiedInstaller/buildout_templates/buildout.cfg /plone/instance/buildout-base.cfg  && pip install pip==$PIP setuptools==$SETUPTOOLS zc.buildout==$ZC_BUILDOUT  && cd /plone/instance  && buildout  && ln -s /usr/local/bin/pip /plone/instance/bin/pip  && ln -s /usr/local/bin/python /plone/instance/bin/python  && ln -s /usr/local/bin/buildout /plone/instance/bin/buildout  && ln -s /data/filestorage/ /plone/instance/var/filestorage  && ln -s /data/blobstorage /plone/instance/var/blobstorage  && chown -R plone:plone /plone /data  && rm -rf /Plone*  && apt-get purge -y --auto-remove $buildDeps  && apt-get install -y --no-install-recommends $runDeps  && rm -rf /var/lib/apt/lists/*  && rm -rf /plone/buildout-cache/downloads/*
 ---> Running in bf4727861eaf
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [452 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [5152 B]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7099 kB]
Fetched 7862 kB in 4s (1889 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils bzip2 cpp cpp-6 gcc-6 icu-devtools libasan3 libatomic1 libc-dev-bin
  libcc1-0 libcilkrts5 libdpkg-perl libffi6 libgcc-6-dev libgmp10 libgnutls30
  libgomp1 libhogweed4 libicu-dev libicu57 libidn11 libidn2-0 libisl15 libitm1
  libjbig-dev libjbig0 libjpeg62-turbo liblsan0 liblzma-dev libmpc3 libmpfr4
  libmpx2 libnettle6 libopenjp2-7 libp11-kit0 libpcre16-3 libpcre32-3
  libpcrecpp0v5 libperl5.24 libpsl5 libquadmath0 libstdc++-6-dev libtasn1-6
  libtiff5 libtiffxx5 libtsan0 libubsan0 libunistring0 libxml2 libxslt1.1
  linux-libc-dev make patch perl perl-modules-5.24 xz-utils
Suggested packages:
  binutils-doc bzip2-doc cpp-doc gcc-6-locales debian-keyring gcc-multilib
  manpages-dev autoconf automake libtool flex bison gdb gcc-doc gcc-6-multilib
  gcc-6-doc libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan3-dbg
  liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libmpx2-dbg
  libquadmath0-dbg glibc-doc gnupg | gnupg2 gnutls-bin icu-doc liblzma-doc
  libstdc++-6-doc pkg-config make-doc ed diffutils-doc perl-doc
  libterm-readline-gnu-perl | libterm-readline-perl-perl
Recommended packages:
  build-essential fakeroot gnupg | gnupg2 libalgorithm-merge-perl bzip2-doc
  manpages manpages-dev libfile-fcntllock-perl liblocale-gettext-perl
  publicsuffix libssl-doc xml-core rename
The following NEW packages will be installed:
  binutils bzip2 cpp cpp-6 dpkg-dev gcc gcc-6 icu-devtools libasan3 libatomic1
  libbz2-dev libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libdpkg-perl libffi6
  libgcc-6-dev libgmp10 libgnutls30 libgomp1 libhogweed4 libicu-dev libicu57
  libidn11 libidn2-0 libisl15 libitm1 libjbig-dev libjbig0 libjpeg62-turbo
  libjpeg62-turbo-dev liblsan0 liblzma-dev libmpc3 libmpfr4 libmpx2 libnettle6
  libopenjp2-7 libopenjp2-7-dev libp11-kit0 libpcre16-3 libpcre3-dev
  libpcre32-3 libpcrecpp0v5 libperl5.24 libpsl5 libquadmath0 libssl-dev
  libstdc++-6-dev libtasn1-6 libtiff5 libtiff5-dev libtiffxx5 libtsan0
  libubsan0 libunistring0 libxml2 libxml2-dev libxslt1-dev libxslt1.1
  linux-libc-dev make patch perl perl-modules-5.24 wget xz-utils zlib1g-dev
0 upgraded, 69 newly installed, 0 to remove and 1 not upgraded.

[...]

--2018-10-25 00:50:32--  https://launchpad.net/plone/5.1/5.1.2/+download/Plone-5.1.2-UnifiedInstaller.tgz
Resolving launchpad.net (launchpad.net)... 91.189.89.223, 91.189.89.222
Connecting to launchpad.net (launchpad.net)|91.189.89.223|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://launchpadlibrarian.net/369528700/Plone-5.1.2-UnifiedInstaller.tgz [following]
--2018-10-25 00:50:32--  https://launchpadlibrarian.net/369528700/Plone-5.1.2-UnifiedInstaller.tgz
Resolving launchpadlibrarian.net (launchpadlibrarian.net)... 91.189.89.228, 91.189.89.229
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|91.189.89.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 63313552 (60M) [application/x-tar]
Saving to: ‘Plone.tgz’

    0K .......... .......... .......... .......... ..........  0%  242K 4m15s

[...]

61800K .......... .......... .........                       100% 1.18M=44s

2018-10-25 00:51:16 (1.39 MB/s) - ‘Plone.tgz’ saved [63313552/63313552]

Plone.tgz: OK
'./Plone-5.1.2-UnifiedInstaller/base_skeleton/base.cfg' -> '/plone/instance/base.cfg'

[...]

'./Plone-5.1.2-UnifiedInstaller/buildout_templates/buildout.cfg' -> '/plone/instance/buildout-base.cfg'
Collecting pip==9.0.3
  Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
Collecting setuptools==38.7.0
  Downloading https://files.pythonhosted.org/packages/f3/8d/74c86edb326ee18c0ffbec9d0a97f6b5a519f6449a64d21673b29e67b8db/setuptools-38.7.0-py2.py3-none-any.whl (490kB)
Collecting zc.buildout==2.11.2
  Downloading https://files.pythonhosted.org/packages/25/ca/6736535c69a7408dbf95f1b48ddf874c11b0e4fda260d97b4d417b9cf96a/zc.buildout-2.11.2-py2.py3-none-any.whl (155kB)
Installing collected packages: pip, setuptools, zc.buildout
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
  Found existing installation: setuptools 40.4.3
    Uninstalling setuptools-40.4.3:
      Successfully uninstalled setuptools-40.4.3
Successfully installed pip-9.0.3 setuptools-38.7.0 zc.buildout-2.11.2
Creating directory '/plone/buildout-cache/downloads'.
Creating directory '/plone/buildout-cache/eggs'.
Getting distribution for 'buildout.wheel==0.2.0'.
warning: no files found matching 'shootout.cfg'
Got buildout.wheel 0.2.0.
Getting distribution for 'six==1.10.0'.
Got six 1.10.0.
While:
  Installing.
  Loading extensions.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2127, in main
    getattr(buildout, command)(args)
  File "/usr/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 638, in install
    self._load_extensions()
  File "/usr/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1174, in _load_extensions
    ep.load()(self)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/plone/buildout-cache/eggs/buildout.wheel-0.2.0-py2.7.egg/buildout/wheel/__init__.py", line 8, in <module>
    import wheel.install
ImportError: No module named install
Removing intermediate container bf4727861eaf
The command '/bin/sh -c buildDeps="dpkg-dev gcc libbz2-dev libc6-dev libjpeg62-turbo-dev libopenjp2-7-dev libpcre3-dev libssl-dev libtiff5-dev libxml2-dev libxslt1-dev wget zlib1g-dev"  && runDeps="gosu libjpeg62 libopenjp2-7 libtiff5 libxml2 libxslt1.1 lynx netcat poppler-utils rsync wv"  && apt-get update  && apt-get install -y --no-install-recommends $buildDeps  && wget -O Plone.tgz https://launchpad.net/plone/$PLONE_MAJOR/$PLONE_VERSION/+download/Plone-$PLONE_VERSION-UnifiedInstaller.tgz  && echo "$PLONE_MD5 Plone.tgz" | md5sum -c -  && tar -xzf Plone.tgz  && cp -rv ./Plone-$PLONE_VERSION-UnifiedInstaller/base_skeleton/* /plone/instance/  && cp -v ./Plone-$PLONE_VERSION-UnifiedInstaller/buildout_templates/buildout.cfg /plone/instance/buildout-base.cfg  && pip install pip==$PIP setuptools==$SETUPTOOLS zc.buildout==$ZC_BUILDOUT  && cd /plone/instance  && buildout  && ln -s /usr/local/bin/pip /plone/instance/bin/pip  && ln -s /usr/local/bin/python /plone/instance/bin/python  && ln -s /usr/local/bin/buildout /plone/instance/bin/buildout  && ln -s /data/filestorage/ /plone/instance/var/filestorage  && ln -s /data/blobstorage /plone/instance/var/blobstorage  && chown -R plone:plone /plone /data  && rm -rf /Plone*  && apt-get purge -y --auto-remove $buildDeps  && apt-get install -y --no-install-recommends $runDeps  && rm -rf /var/lib/apt/lists/*  && rm -rf /plone/buildout-cache/downloads/*' returned a non-zero code: 1
```

**Comment by avoinea** [comment]
Plone 5.1.4 Released https://github.com/docker-library/official-images/pull/5014

**Comment by agschaid** [comment]
nope. 5.1.4 does NOT fix it.
The problem is that the install command was removed in in wheels version 0.32.0

@lag-linaro you probably want to pin your wheels version to 0.31.1 in your buildout.cfg
@avoinea you might want to do the same in Plone 5.1.5

it might be worth noting: me and a colleague (both Linux) had that problem while another (on Windows subsystem) didn't. Probably he didn't have the newest wheels version accessible.

**Comment by lag-linaro** [comment]
Right.  The issue that I reported is fixed and should be closed.

If you know of a different issue, please submit it separately.

Closing this issue.
