### ISSUE TITLE
PermissionError when building custom image based on Plone 5.2.*

### ISSUE THREAD

**Issue by sjloyola** [plone/plone.docker#129]
Any idea what could be causing even the simplest of custom images based on Plone 5.2.* to fail as detailed below? Thanks!

I can't get my projects to build with the Plone 5.2.1 Docker image so I created a test directory with what I would think is the simplest Dockerfile and custom site.cfg possible and yet ```docker build``` still fails.

Dockerfile:
```
FROM plone:5.2.1

COPY site.cfg /plone/instance/
RUN gosu plone buildout -c site.cfg
```

site.cfg:
```
[buildout]
extends = buildout.cfg
```

On both Mac OS X v10.14 and CentOS Linux v7, running ```docker build -t custom-plone-image .``` fails with this output:

```
  File "/plone/buildout-cache/eggs/zodbpickle-1.0.4-py3.7-linux-x86_64.egg/zodbpickle/tests/pickletester_2.py", line 433
    x = [0, 1L, 2.0, 3.0+0j]
             ^
SyntaxError: invalid syntax

While:
  Updating precompiler.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/usr/local/lib/python3.7/site-packages/zc/buildout/buildout.py", line 787, in install
    installed_files = self[part]._call(update)
  File "/usr/local/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/plone/buildout-cache/eggs/plone.recipe.precompiler-0.7.1-py3.7.egg/plone/recipe/precompiler/__init__.py", line 32, in update
    return self._run()
  File "/plone/buildout-cache/eggs/plone.recipe.precompiler-0.7.1-py3.7.egg/plone/recipe/precompiler/__init__.py", line 35, in _run
    self._compile_eggs()
  File "/plone/buildout-cache/eggs/plone.recipe.precompiler-0.7.1-py3.7.egg/plone/recipe/precompiler/__init__.py", line 67, in _compile_eggs
    py_compile.compile(fn, None, None, True)
  File "/usr/local/lib/python3.7/py_compile.py", line 169, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 112, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/__pycache__/easy_install.cpython-37.pyc.139945220652592'
The command '/bin/sh -c gosu plone buildout -c site.cfg' returned a non-zero code: 1
```

(I included the SyntaxError even though I don't think that's related since I see in issue #125 that @avoinea got similar errors with no negative effects.)

If I switch the Dockerfile to be FROM plone:5.1.6 (or earlier version), the image builds just fine.

Thanks for any insights!

**Comment by sjloyola** [comment]
Thanks to @nutjob4life for the brilliant solution to my PermissionError. Just make sure Python is owned by the plone user with a well-placed "chown".

```FROM plone:5.2.1

COPY site.cfg /plone/instance/
RUN chown -R plone:plone /usr/local/lib/python3.7
RUN gosu plone buildout -c site.cfg```

**Comment by nutjob4life** [comment]
Aww, shucks. Thanks @sjloyola 😉

I would't close this just yet though. This is just a bandaid, not a solution. (And if it's indeed _the_ solution, it should be documented.)

**Comment by avoinea** [comment]
Hmmm... the `chown /usr/local/bin/python` hack doesn't look right. You should do:

```
FROM plone:5.2.1

COPY site.cfg /plone/instance/
RUN buildout -c site.cfg \
 && chown -R plone:plone /data /plone
```

or with better results:

```
FROM plone:5.2.1

COPY site.cfg /plone/instance/
RUN buildout -c site.cfg \
 && find /data  -not -user plone -exec chown plone:plone {} \+ \
 && find /plone -not -user plone -exec chown plone:plone {} \+ \
```

I will upgrade the docs.

**Comment by avoinea** [comment]
@nutjob4life @sjloyola 

Fixed https://github.com/plone/plone.docker/blob/master/docs/container-images/custom.rst#dockerfile
