### ISSUE TITLE
Getting error on bin/zeopack

### ISSUE THREAD

**Issue by caduvieira** [plone/plone.docker#37]
Getting the following error on bin/zeopack

" Traceback (most recent call last):
  File "/plone/instance/bin/zeopack", line 40, in <module>
    sys.exit(plone.recipe.zeoserver.pack.main(host, port, unix, days, username, password, realm, blob_dir, storage))
...
  File "/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/blob.py", line 336, in __init__
    self.layout = LAYOUTS[layout_name]
KeyError: 'zeocache' "

More on:
https://gist.github.com/caduvieira/8e5454262ca60b563e4c49c52dde0dea

**Comment by caduvieira** [comment]
Fix by setting ZEO_SHARED_BLOB_DIR to on and recreate the volumes.
